mindmap
Forcepoint Help
  Forcepoint DLP Administrator Help
  Overview
    Data classification
    Managing Forcepoint DLP
    Forcepoint DLP databases
    Forcepoint DLP basics
    Forcepoint DLP appliances
    What can I protect?
    DLP in Forcepoint Web Security and Forcepoint Email Security
  Navigating the system
    Main options
      Reporting
      Status
      Policy Management
      Logs
    Deploy button
    Settings options
      General
      Deployment
      Authorization
    Global and status icons
  Initial Setup
    Configuring the protector
    Configuring system modules
    Defining general system settings and notifications
    Entering a subscription key
  Viewing Status
    Changing table properties
    Viewing endpoint status
    Viewing the Dashboard
      Health Alert Summary
      SSL Certificate Alerts
      Discovery Incidents
      Business Value
      Data Loss Prevention Incidents
    Monitoring system health
    Viewing deployment status
    Applying column filters
  Viewing Incidents and Reports
    Viewing the incident list
      Toolbar buttons
      Remediating incidents
      Managing incident workflow
      Previewing incidents
      Managing incident reports
        Editing table properties
        Applying a column filter
      Escalating incidents
      Tuning policies
    The report catalog
      Scheduling tasks
        Scheduling a new task
      Editing a report
        Table Properties tab
    Discovery reports
      Discovery dashboard
    Data Loss Prevention reports
      Incidents by geographical location
  Policies Overview
    Viewing policies
      The policy toolbar
      Update rules of a current policy
      Editing a policy
      Update rules of multiple policies
      Update exceptions of multiple rules
      Update exceptions of current rule
      Policy levels
      Delete policies
    What’s in a policy?
    Selecting items to include or exclude in a policy
    Import and Export policies from Forcepoint Security Manager
  Configuring the Email DLP Policy
    Defining email DLP policy owners
    Configuring outbound and inbound email DLP attributes
    Identifying email DLP trusted domains
  Configuring the Web DLP Policy
    Selecting web DLP policy destinations
    Configuring web DLP policy attributes
    Web DLP policy configuration overview
    Defining web DLP policy owners
  Using Predefined DLP and Discovery Policies
    Changing the selected DLP or discovery policies
    Adding a predefined DLP or discovery policy
    Changing policy industry or region settings
  Creating Custom DLP Policies
    Custom Policy Wizard - Source
    Custom Policy Wizard - General
    Custom Policy Wizard - Severity and Action
    Custom Policy Wizard - Condition
    Managing exceptions
    Selecting a content classifier
    Rule Wizard - Finish
    Managing rules
    Custom Policy Wizard - Destination
  Classifying Content
    Patterns &amp; Phrases
    Details pane
    Content classifier menu bar
    Manually deleting fingerprinting classifiers
    Database fingerprinting
    File fingerprinting
    Scripts
    File properties
    File Labeling
    Creating a rule from a content classifier
    Machine learning
    Imported fingerprinting
    Database Fingerprinting Wizard - Scheduler
  Defining Resources
    Cloud resources
    Remediation resources
    Endpoint resources
    User directory entries
    General resources
    Custom users
    Domains
    Custom computers
    Networks
    Custom user directory groups
    Endpoint Devices
    Endpoint Application Groups
    Endpoint Applications
    URL categories
    Business Units
    Remediation
    Notifications
      Adding a new message
    Endpoint Printers
  Creating Discovery Policies
    Creating a discovery policy
    Performing Domino discovery
    Scheduling the discovery scan
    Performing file system discovery
    Performing SharePoint discovery
    Performing Box discovery
    Performing database discovery
    Performing Exchange discovery
    Performing endpoint discovery
    Performing Outlook PST discovery
    Viewing discovery status
    Configuring discovery incidents
    Updating discovery
    Copying or moving discovered files
    Viewing discovery results
  Scheduling Discovery Tasks
    Emailing discovery task status reports
    Sorting and filtering tasks
    Scheduling network discovery tasks
    Configuring cloud discovery scans
    Adding or editing a cloud discovery scan
    Scheduling endpoint discovery tasks
  Viewing Forcepoint DLP Logs
    Printing and exporting logs
    Filtering log data
    The Forcepoint DLP traffic log
    The Forcepoint DLP audit log
    The Forcepoint DLP system log
    The Forcepoint DLP debug log
  General System Settings
    Setting reporting preferences
      Setting preferences for data loss prevention reports
    Configuring endpoint settings
    Remediation
    Exporting incidents to a file
    Backing up the system
    Mail servers
    Alerts
      Setting up email properties
    Analytics
    Services
    Archive storage
    User directory settings
      Adding or editing user directory server information
    Updating predefined policies and classifiers
    Archiving incident partitions
    Entering subscription settings
  Configuring Authorization
    Defining administrators
    Working with roles
    Customizing your own administrator account settings
  Managing Forcepoint DLP System Modules
    Adding Forcepoint DLP system modules
      Configuring the forensics repository
      Configuring the protector
        Edit Protector: Services tab
        Edit Protector: General tab
        Edit Protector: Networking tab
        Edit Protector: Local Networks tab
      Configuring Forcepoint DLP system modules
    Configuring protector services
    Balancing the load
    Removing Forcepoint DLP modules
  Configuring Endpoint Deployment
    Viewing and managing endpoint profiles
    Configuring encryption for removable media
    Bypassing endpoint clients
    Rearranging and deploying endpoint profiles
    Selecting endpoint destination channels to monitor
    Using the endpoint client software
  Troubleshooting
    Discovery
    Incidents
    Fingerprinting
    Endpoint
    Miscellaneous
    Online Help
    Linking Service
    Performance
    Technical Support
    Known Issues and Limitations
    Uninstall Agents
    Starting and Stopping Services
    Troubleshooting Agent and Classifier Paths
    Verifying Client Information
    Troubleshooting Services
    Troubleshooting Processes
  Appendix A: How Do I
    Archive my incident data?
    Define an exception?
    Filter incidents?
    Configure a DLP policy?
    Ignore sections of my document when fingerprinting?
    Mitigate false positives in pattern or dictionary phrases?
    Fingerprint specific field combinations in a database table?
    Fingerprint data?
    Move from monitor to protect?
  Forcepoint Security Manager Help
  DLP Installation Guide
  Forcepoint Data Security Cloud Online Help
  Forcepoint ONE | Firewall Online Help
  Forcepoint  Neo
  Forcepoint Data Security Sitemap
  Forcepoint DLP for Cloud Email Sitemap
  Forcepoint Data Visibility Powered by GetVisibility Sitemap
  Forcepoint Data Classification
  Remote Browser Isolation Sitemap
  Boldon James Classifier Enterprise Suite Sitemap
  Forcepoint Data Security Cloud | SSE Sitemap
  F1E-SEA Agent Co-existence Feature Enablement
  Forcepoint Insights Documentation Sitemap
  Forcepoint DSE Agent
  Forcepoint ONE Mobile Sitemap
  Endpoint Management
  Setup traffic steering
    Deploying SmartEdge Agent
      Requirements for SmartEdge Agent installation
      Best practices for rolling SmartEdge Agents with policies
      Allowing domains for SmartEdge Agents
      Allowing on endpoint management agents
      Installing SmartEdge Agent on macOS
      Installing SmartEdge Agent on Windows
      Manually trusting certificates on macOS
      SmartEdge Agent and F1A Interoperability
      Deploying SmartEdge Agents via MDM to wider audience
    Deploying Cloud SWG
    Configuring SWG settings
    Deploying Mobile Agent
  Forcepoint Email Security On-premises Documentation
  Forcepoint Email Security Cloud Sitemap
  Forcepoint F1E Documentation
  Advanced Malware Detection and Protection Sitemap
  NGFW Appliances Sitemap
  Forcepoint V-Series and Virtual Appliances Sitemap
  URL Filtering Sitemap
  FlexEdge Secure SD-WAN Sitemap
  Data Loss Prevention DLP Sitemap
  Web Security Cloud Sitemap
  Web Security Sitemap
  Next Generation Firewall NGFW Sitemap
  Introduction
    Help and support
      support.forcepoint.com
        Help and support
    About the Forcepoint DSE Agent
    About the agent for Forcepoint Cloud Security Gateway
    Endpoint management
  Product updates
    Resolved and Known Issues
    Whats New
    Previous release updates
    Whats new
  Understanding Forcepoint Data Security Cloud layout
    Accessing the online help documentation
    Viewing the tenants Reference IDs
    Changing the password
  Signing in to Forcepoint Data Security Cloud
  Platform services
    Insights
    Admin
    Settings
  Applications
    Remote Browser Isolation
    Web Security
    DLP
    Security Service Edge
  Product Updates
    Known and resolved issues
  Getting Started
    Accessing Forcepoint ONE | Firewall
    Accessing Forcepoint ONE | Secure Service Edge
    Workflow for new users
    Workflow for existing users
  Forcepoint ONE | Firewall overview
    Deploy changes
    Accessing the online help documentation
  Logs
    Event detail panel
    Related events
  Dashboard
    Dashboard filters
    Time period drop-down menu
  Policy
    All Policies Page Overview
  Log Export
    AWS Access Key and Secret Key
  Objects
    Threat Situations
    Network &amp; HTTP/3 Applications
      Network &amp; HTTP/3  Applications
    Sites
    Network Services
    Domain Name lists
    Destination IP Address Lists
    Source IP address lists
  Deploy History
  Forcepoint DLP for Cloud Email Legal Notices and Acknowledgments
  Forcepoint DLP for Cloud Email Online Help
  Data Security Cloud | DLP - 3rd Party Legal Notices and Acknowledgement
  Forcepoint Data Security Cloud | DLP
  Forcepoint DSPM Documentation
  Forcepoint Cloud DSPM Documentation
  Remote Browser Isolation | Help
  RBI Legal Notices and Acknowledgments
  Boldon James Release Note
  Release%20Note.htm
  Documentation Release Note
  Box%20Classifier%20Release%20Notes.htm
  PowerShell%20Release%20Note.htm
  Website%20For%20Clients%20Release%20Note.htm
  Forcepoint Data Security Cloud | SSE Deployment Guide
  Forcepoint ONE SSE 240924 Release Notes
  Forcepoint ONE SSE 240321 Release Notes
  Forcepoint ONE SSE 231023 Release Notes
  Forcepoint ONE SSE 231220 Release Notes
  Forcepoint ONE SSE Production 230516 Release Notes
  Forcepoint ONE SSE Production 230814 Release Notes
  Forcepoint ONE Production 230112 Release Notes
  Forcepoint ONE Production Gov Cloud 220805 Release Notes
  Forcepoint ONE Production 221116 Release Notes
  Forcepoint ONE Production 220805 Release Notes
  Forcepoint ONE Canada Gov Cloud 220805 Release Notes
  Forcepoint ONE Production 230329 Release Notes
  Forcepoint ONE Production Gov Cloud 230112 Release Notes
  Forcepoint ONE Production 220609 Release Notes
  Forcepoint ONE Production 220331 Release Notes
  Forcepoint ONE SSE SmartEdge Agent 2.3.0 for Windows - Release Notes
  Forcepoint Data Security Cloud | SSE SmartEdge Agent 3.0.0 for Windows - Release Notes
  Forcepoint ONE SSE SmartEdge Agent 2.1.0 for macOS - Release Notes
  Forcepoint ONE SSE SmartEdge Agent 2.4.0 for Windows - Release Notes
  Forcepoint ONE Gov Cloud 220214 Release Notes
  Forcepoint ONE SSE SmartEdge Agent 2.4.0 for macOS - Release Notes
  Forcepoint ONE Production 220214 Release Notes
  Forcepoint ONE SmartEdge FIPS Agent 1.6.3-F for Windows - Release Notes
  Forcepoint DLP and Forcepoint Data Security Cloud | SSE CASB Integration Guide
  How to Connect Cisco ASA/FTD to Forcepoint ONE Cloud over IPsec Tunnel
  How to Connect Forcepoint NGFW to Forcepoint ONE Cloud over IPsec Tunnel
  How to Connect Cisco ISR to Forcepoint ONE Cloud over IPsec Tunnel
  How to Connect Palo Alto to Forcepoint ONE Cloud over IPsec Tunnel
  How to Connect Cisco ISR to Forcepoint ONE Cloud over GRE Tunnel
  How to Connect Juniper SRX to Forcepoint ONE Cloud over GRE Tunnel
  Forcepoint DLP and Forcepoint Data Security Cloud | SSE SWG Integration Guide
  How to Connect Juniper SRX to Forcepoint ONE Cloud over IPsec Tunnel
  Insights User Guide
  Configuring Forcepoint Data Security Cloud | SSE for Agent Co-existence
  Configuring Web Security for Agent Co-existence
  How to Connect any Edge Device to Forcepoint ONE Cloud over IPsec Tunnel
  Forcepoint Insights - API Documentation
  Removing the agent
    Generating the release code
    Removing the agent on Windows
    Removing the agent on maC
  Deploying the agent
    System requirements
    Prerequisites
    Windows Installation
    Downloading the agent
  Endpoint management
    Updating the Forcepoint agent
    Profiles
    My Endpoints
    Agent Compatibility
    Viewing the agent status
  Release Notes
    Known Issues
  Forcepoint Mobile Online Help
  Forcepoint Mobile Acknowledgment of Third-party Software
  Installing the agent
    macOS installation
    System requirements
    Windows Installation
    Before you begin
    Downloading the agent
  Updating the agent
    Updating the agent manually
    Over the air updates
  Configuring the agent
    Configuring the agent pac file
    Configuring the agent operating mode - on-prem or cloud
    Configuring the agent connection mode
  Viewing the agent status
    Viewing the agent status on Forcepoint Data Security Cloud | DLP portal
    Viewing the agent status on Forcepoint Cloud Security Gatewayportal
  Migrating from Forcepoint F1E to the Forcepoint agent
    Forcepoint customer             support
      Migrating from Forcepoint F1E to the Forcepoint agent
      Migrate from Forcepoint F1E to the new agent
  Agent Compatibility
  Verify access and perform initial configuration
  Understanding User and Groups
  Configure common components
  Configure Zero Trust Network Access
  Configure DLP
  Protect cloud applications
  Configure policies
  Forcepoint Email Security | Release Notes v8.5.7
  Email Security | Release Notes v8.5.5
  Configure applications
  v8.5.4 Release Notes for the Forcepoint Security Manager
  Email Security | Installation Guide v8.5.x
  Web Security, DLP, and Email Security | Security Solutions Installation Guide
  Email Security | Upgrade Guide v8.5.x
  Deployment Quick Reference
    Default ports for on-premises Forcepoint security solutions
  Forcepoint DLP Deployment and Installation Center
  Web Security, DLP, and Email Security | Security Solutions Upgrade Guide
  Email Security | Installing Email Security in Microsoft Azure v8.5.x
  Email Security Gateway | Online Help
  Data, Email, and Web Security | Backup and Restore FAQ
  Email Security | Secure Messaging User Help: Localized Versions
  Email Security | Message Encryption v8.5.x
  Data, Email, and Web Security | Moving the Management Server
  Data, Email, and Web Security | Moving the Reporting Databases
  Email Security | Security Information Event Management SIEM: Email Logs v8.5.x
  Email Security Ports v8.5.x
  Email Security | Acknowledgment of Third-party Software v8.5.x
  Email Security Cloud 2024: Release Notes
  Email Security Cloud 2025: Release Notes
  Email Security Cloud 2023: Release Notes
  Email Security Cloud 2022: Release Notes
  Forcepoint Email Security Cloud: 2020 Release Notes
  Forcepoint Email Security Cloud: 2021 Release Notes
  Email Security Cloud | Managing Cloud Email Protection Products
  Forcepoint Email Security Cloud: 2019 Release Notes
  Email Security Cloud | Online Help
  Email Security Cloud | Getting started with SIEM Integration
  Email Security Cloud | End User Guide
  Release Notes for Forcepoint F1E
  Forcepoint F1E Install Guide
  Deploying Forcepoint DLP Endpoint on Citrix virtual environments
  Forcepoint F1E Upgrade Guide
  Endpoint Applications
  Automatic Updates for Forcepoint F1E Forcepoint DLP Endpoint
  Forcepoint F1E End User Guide
  Security Appliance Manager Release Notes
  Security Appliance Manager Installation Guide
  Security Appliance Manager FSAM Administrator Help
  Security Appliance Manager Troubleshooting Guide
  v8.5.7 Release Notes for Forcepoint Appliances
  v8.5.6 Release Notes for Forcepoint Appliances
  Forcepoint Product Documentation Sitemap
